version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

  metabase:
    image: metabase/metabase
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=mss-journal
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=
      - MB_DB_HOST=db
    networks:
      - postgres
    ports:
      - "3000:3000"
    depends_on:
      - db

  # https://github.com/nodejs/docker-node/blob/main/README.md#how-to-use-this-image
  node:
    image: node:18.12.1 # Version LTS
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
    command: "./scripts/migrations.sh"
    networks:
      - postgres
    depends_on:
      - db

networks:
  postgres:
